version: "3.7"
services:
  my-custom-app1:
    image: bibiefrat:mongo
    ports:
      - "8882:80"
    networks:
        - network2
    volumes: 
      - volume_demo:/data1:rw
    environment:
      MONGO_URL_RUN: "mongodb://10.100.1.143:20000"

  my-custom-app2:
    image: bibiefrat:mongo
    ports:
      - "8883:80"
    networks: 
      - network2
    volumes:
      - volume_demo2:/data2:rw
    environment:
      MONGO_URL_RUN: "mongodb://10.100.1.143:20000"

networks:
  network2: {}


volumes:
  volume_demo:

  volume_demo2:
